"""Attach an autonomous EFG result to an existing 17-key run bundle."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from pegasus.core.hashing import sha256_file
from pegasus.efg.dag import EFGResult
from pegasus.efg.lineage import lineage_hash
from pegasus.output.validate import validate_output_bundle
from pegasus.storage import append_replace, read_table, write_table


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)


def _read_rows(path: Path) -> list[dict[str, Any]]:
    return read_table(path).to_pylist()


def _write_rows(path: Path, rows: list[dict[str, Any]]) -> None:
    write_table(path, rows, schema_policy="preserve")


def _append_replace(path: Path, rows: list[dict[str, Any]], *, id_column: str) -> None:
    append_replace(path, rows, id_column=id_column)


def _v_row(field) -> dict[str, Any]:
    warnings = list(dict.fromkeys([*field.warnings, "autonomous_efg_metadata_only"]))
    return {
        "field_id": field.id,
        "name": field.name,
        "kind": field.kind,
        "carrier": field.carrier,
        "unit": field.unit,
        "aggregation": field.aggregation,
        "role": _json(field.role),
        "source": _json(field.source),
        "support_json": _json(field.support),
        "axes_json": _json(field.axes),
        "operator": field.operator,
        "provenance": _json(field.provenance),
        "state": "quarantined_descriptive",
        "dashboard_safe": "False",
        "warnings": _json(warnings),
        "lineage_hash": lineage_hash(field.lineage),
        "registry_hash": str(field.lineage.registry_versions.get("efg_operator_registry", "slice19a")),
        "materialization_state": field.materialization_state.value,
        "path": field.path,
    }


def _q_row(field) -> dict[str, Any]:
    missingness = field.support.get("missing_rate")
    return {
        "field_id": field.id,
        "n_events": float(field.support.get("row_count") or 0.0),
        "n_denom": None,
        "n_eff": float(field.support.get("non_null_count") or 0.0),
        "cov_S": None,
        "cov_T": None,
        "missingness": float(missingness) if missingness is not None else None,
        "zero_inflation": None,
        "denom_fragility": 1.0,
        "cv": None,
        "moran_i": None,
        "temporal_roughness": None,
        "spatial_entropy": None,
        "provenance_risk": 0.75,
        "race_axis_source": field.axes.get("race_axis_type"),
        "race_axis_target": None,
        "missing_race_share": None,
        "emission_prior_strength": None,
        "race_bridge_cv": None,
        "sensitivity_width": None,
        "bridge_mode": None,
        "state": "quarantined_descriptive",
        "dashboard_safe": "False",
        "warnings": _json(["autonomous_efg_metadata_only", "q_tensor_no_materialized_tensor"]),
        "computed_at": _now(),
        "q_schema_version": "1.0",
    }


def _dictionary_row(field, metadata: dict[str, Any]) -> dict[str, Any]:
    warning = metadata.get("interpretation_warning") or "Autonomous EFG metadata node; numerical tensor not materialized."
    return {
        "field_id": field.id,
        "display_name": metadata.get("display_name", field.name),
        "technical_name": metadata.get("technical_name", field.name),
        "definition": metadata.get("definition", f"Autonomous EFG node generated by {field.operator}."),
        "estimand_label": metadata.get("estimand_label", field.kind),
        "source_systems": _json(metadata.get("source_systems", field.source)),
        "carrier": field.carrier,
        "unit": field.unit,
        "support_description": _json(field.support),
        "axis_description": _json(field.axes),
        "provenance_description": _json(field.provenance),
        "state": "quarantined_descriptive",
        "dashboard_safe": "False",
        "interpretation_warning": warning,
    }


def _warning_row(field) -> dict[str, Any]:
    return {
        "warning_id": f"autonomous_efg_metadata_only_{field.id}",
        "field_id": field.id,
        "source": "pegasus.efg.compile_attach",
        "severity": "info",
        "code": "autonomous_efg_metadata_only",
        "message": "Autonomous EFG node is graph-authoritative metadata without a materialized numerical tensor.",
        "inherited_from": _json(field.warnings),
        "created_at": _now(),
    }


def _quarantined_row(field) -> dict[str, Any]:
    return {
        "field_id": field.id,
        "state": "quarantined_descriptive",
        "reason": "autonomous_efg_node_without_materialized_tensor",
        "warnings": _json(["autonomous_efg_metadata_only", "q_tensor_no_materialized_tensor"]),
    }


def _edge_row(edge) -> dict[str, Any]:
    return {
        "edge_id": edge.edge_id,
        "parent_field_id": edge.parent_field_id,
        "child_field_id": edge.child_field_id,
        "operator": edge.operator,
        "operator_params_json": _json(edge.operator_params),
        "registry_versions_json": _json(edge.registry_versions),
        "created_at": edge.created_at,
    }


def _failed_row(branch) -> dict[str, Any]:
    return {
        "failed_branch_id": branch.failed_branch_id,
        "attempted_operator": branch.attempted_operator,
        "parent_field_ids": _json(branch.parent_field_ids),
        "failure_stage": branch.failure_stage,
        "failed_terms": _json(branch.failed_terms),
        "reason": branch.reason,
        "warnings": _json(branch.warnings),
        "created_at": branch.created_at,
    }


@dataclass(frozen=True)
class AutonomousEFGAttachResult:
    run_dir: str
    manifest_path: str
    manifest_hash: str
    efg_id: str
    field_count: int
    edge_count: int
    failed_branch_count: int
    output_validation_ok: bool

    def as_manifest(self) -> dict[str, Any]:
        return {
            "schema_version": "19B.1",
            "status": "attached",
            "run_dir": self.run_dir,
            "manifest_path": self.manifest_path,
            "manifest_hash": self.manifest_hash,
            "efg_id": self.efg_id,
            "field_count": self.field_count,
            "edge_count": self.edge_count,
            "failed_branch_count": self.failed_branch_count,
            "output_validation_ok": self.output_validation_ok,
            "graph_authority": "autonomous_efg_core",
            "legacy_computed_fields_preserved": True,
            "first_class_output_keys_added": 0,
        }


def attach_autonomous_efg_to_run(
    *,
    run_dir: str | Path,
    result: EFGResult,
    validate: bool = True,
) -> AutonomousEFGAttachResult:
    root = Path(run_dir)
    tables = root / "Tables"
    tables.mkdir(parents=True, exist_ok=True)
    manifest_path = tables / "efg_autonomous_manifest.json"
    manifest_path.write_text(
        json.dumps(result.as_manifest(), indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    dictionary = {str(item["field_id"]): item for item in result.variable_dictionary}

    _append_replace(root / "V_fields.parquet", [_v_row(field) for field in result.fields], id_column="field_id")
    _append_replace(root / "Q_tensor.parquet", [_q_row(field) for field in result.fields], id_column="field_id")
    _append_replace(
        root / "VariableDictionary.parquet",
        [_dictionary_row(field, dictionary.get(field.id, {})) for field in result.fields],
        id_column="field_id",
    )
    _append_replace(root / "Warnings.parquet", [_warning_row(field) for field in result.fields], id_column="warning_id")
    _append_replace(
        root / "QuarantinedFields.parquet",
        [_quarantined_row(field) for field in result.fields],
        id_column="field_id",
    )
    _append_replace(root / "E_DAG.parquet", [_edge_row(edge) for edge in result.edges], id_column="edge_id")
    _append_replace(
        root / "FailedBranches.parquet",
        [_failed_row(branch) for branch in result.failed_branches],
        id_column="failed_branch_id",
    )

    validation_ok = True
    if validate:
        validation = validate_output_bundle(run_dir=str(root))
        validation_ok = validation.ok
        if not validation.ok:
            raise ValueError("Autonomous EFG attachment invalidated run bundle: " + "; ".join(validation.errors))
    return AutonomousEFGAttachResult(
        run_dir=str(root),
        manifest_path=str(manifest_path.relative_to(root)).replace("\\", "/"),
        manifest_hash=sha256_file(manifest_path),
        efg_id=result.efg_id,
        field_count=result.field_count,
        edge_count=result.edge_count,
        failed_branch_count=len(result.failed_branches),
        output_validation_ok=validation_ok,
    )
