"""Standalone helpers for the autonomous EFG compiler core."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from pegasus.core.hashing import content_hash, sha256_file
from pegasus.core.schemas import FieldNode
from pegasus.efg.declaration import OperatorSpec
from pegasus.efg.lineage import lineage_hash, make_lineage
from pegasus.efg.node import make_field_node
from pegasus.efg.operators import EFGOperator
from pegasus.she.substrate import SubstrateBundle

__all__ = [
    "_now",
    "EFGEdge",
    "_empty_core_seed_summary",
    "_empty_bridge_plan_summary",
    "_edge",
    "_registry_hashes",
    "_source_hashes",
    "_dictionary",
    "_event_groups",
    "_ratio_role",
    "_find_field",
    "_race_bridge_source",
    "_append_race_bridge_fields",
    "_field_domain_summaries",
    "_dedupe_edges",
]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass(frozen=True)
class EFGEdge:
    edge_id: str
    parent_field_id: str
    child_field_id: str
    operator: str
    operator_params: dict[str, Any]
    registry_versions: dict[str, str]
    created_at: str

    def as_manifest(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["operator_params_json"] = dict(self.operator_params)
        payload["registry_versions_json"] = dict(self.registry_versions)
        return payload


def _empty_core_seed_summary(registry_root: str | Path = "config/registries") -> dict[str, Any]:
    return {
        "registry_root": str(registry_root),
        "seed_count": 0,
        "blocked_count": 0,
        "role_counts": {},
        "seeds": [],
        "blocked": [],
    }


def _empty_bridge_plan_summary() -> dict[str, Any]:
    return {
        "candidate_count": 0,
        "blocked_count": 0,
        "bridge_type_counts": {},
        "candidates": [],
        "blocked": [],
    }


def _edge(
    parent: FieldNode,
    child: FieldNode,
    operator: OperatorSpec,
    *,
    edge_operator: str | None = None,
    edge_params: dict[str, Any] | None = None,
) -> EFGEdge:
    operator_name = edge_operator or operator.name
    params = {**operator.params, **(edge_params or {})}
    payload = {
        "parent": parent.id,
        "child": child.id,
        "operator": operator_name,
        "params": params,
    }
    versions = dict(child.lineage.registry_versions)
    return EFGEdge(
        edge_id=f"edge_{content_hash(payload)[:24]}",
        parent_field_id=parent.id,
        child_field_id=child.id,
        operator=operator_name,
        operator_params=params,
        registry_versions=versions,
        created_at=_now(),
    )


def _registry_hashes(substrate: SubstrateBundle, root: Path) -> dict[str, str]:
    hashes = dict(substrate.registry_hashes)
    for name in (
        "datasus/source_fields.yaml", "ontology/carrier.yaml", "ontology/unit.yaml", "ontology/aggregation.yaml",
        "ontology/provenance.yaml", "ontology/quality.yaml", "ontology/quality_permissions.yaml",
        "health/cnes_capacity_registry.yaml", "health/sih_cost_registry.yaml", "health/diagnostic_topology.yaml",
    ):
        path = root / name
        if path.exists():
            hashes[name] = sha256_file(path)
    hashes["efg_operator_registry"] = content_hash({
        "version": "slice19a",
        "operators": [operator.value for operator in EFGOperator],
    })
    return hashes


def _source_hashes(substrate: SubstrateBundle) -> tuple[str, ...]:
    return tuple(sorted({
        value
        for artifact in substrate.source_artifacts
        for value in (artifact.source_manifest_hash, artifact.artifact_hash)
        if value
    }))


def _dictionary(field: FieldNode) -> dict[str, Any]:
    diagnostic_role = field.axes.get("icd_topology_role") or field.axes.get("diagnostic_role")
    return {
        "field_id": field.id,
        "display_name": field.name,
        "technical_name": field.name,
        "definition": f"EFG field generated by {field.operator or 'substrate admission'}.",
        "estimand_label": next((role for role in field.role if role.endswith("rate")), field.kind),
        "source_systems": list(field.source),
        "carrier": field.carrier,
        "unit": field.unit,
        "support_description": dict(field.support),
        "axis_description": dict(field.axes),
        "provenance_description": list(field.provenance),
        "state": field.state.value,
        "dashboard_safe": field.dashboard_safe,
        "interpretation_warning": ";".join(field.warnings) or None,
        "diagnostic_role": diagnostic_role,
        "topology": diagnostic_role,
        "position": field.axes.get("position"),
        "capacity_index": field.axes.get("capacity_index") or field.axes.get("capacity_family"),
        "cost_component": field.axes.get("cost_component"),
    }


def _event_groups(
    fields: Iterable[FieldNode], *, registry_root: str | Path = "config/registries"
) -> dict[tuple[str, str], list[FieldNode]]:
    from pegasus.registries.events import primary_event_carriers

    countable = primary_event_carriers(root=registry_root)
    groups: dict[tuple[str, str], list[FieldNode]] = {}
    for field in fields:
        artifact = field.support.get("artifact_path")
        carrier = field.carrier
        if carrier == "FacilityCapacityVector" and "Facilities" in countable and "cnes_capacity_component" in set(field.role or []):
            carrier = "Facilities"
        if not artifact or carrier not in countable:
            continue
        if field.unit == "ICD10" or "diagnostic_topology" in field.role:
            continue
        groups.setdefault((str(artifact), carrier), []).append(field)
    return groups


def _ratio_role(
    numerator: FieldNode, denominator: FieldNode, *, registry_root: str | Path = "config/registries"
) -> str:
    """Resolve the estimand label for a (numerator, denominator) carrier pair.

    Driven by the clinical event registry (MSD §2.6) — the engine holds no
    hardcoded carrier→role table.
    """
    from pegasus.registries.events import clinical_ratio_specs

    for spec in clinical_ratio_specs(root=registry_root):
        if spec.numerator_carrier == numerator.carrier and spec.denominator_carrier == denominator.carrier:
            return spec.role
    return "unsupported_ratio"


def _find_field(fields: list[FieldNode], selector: str) -> FieldNode | None:
    return next((field for field in fields if field.id == selector or field.name == selector), None)


def _race_bridge_source(fields: Iterable[FieldNode], plan: dict[str, Any]) -> FieldNode | None:
    source_system = str(plan.get("source_system") or "SIM-DO")
    for field in fields:
        roles = set(field.role or [])
        if source_system not in set(field.source or []):
            continue
        if "administrative_race_axis" in roles or field.support.get("column") == "race_color_admin":
            return field
    return None


def _append_race_bridge_fields(
    *,
    fields: list[FieldNode],
    edges: list[EFGEdge],
    constraints: dict[str, Any],
    warnings: list[str],
) -> None:
    plan = constraints.get("race_bridge_plan")
    if not isinstance(plan, dict) or plan.get("status") != "planned":
        return
    parent = _race_bridge_source(fields, plan)
    if parent is None:
        warnings.append("race_bridge_source_axis_not_found")
        return
    prior_path = plan.get("prior_path")
    prior_hash = plan.get("prior_hash")
    params = {
        "bridge_id": plan.get("bridge_id"),
        "bridge_operator": "Bridge_R_localPi_posteriorC",
        "bridge_mode": plan.get("mode") or "localPi_posterior",
        "source_axis": plan.get("source_axis"),
        "target_axis": plan.get("target_axis"),
        "prior_path": prior_path,
        "prior_hash": prior_hash,
        "raw_admin_counts_preserved": True,
        "missing_category_preserved": True,
    }
    support = {
        **dict(parent.support),
        **params,
        "missing_race_share": 0.0,
        "race_bridge_cv": 0.0,
        "sensitivity_width": 0.0,
        "emission_prior_strength": 1.0,
    }
    axes = {
        **dict(parent.axes),
        "numerator_axis_source": plan.get("source_axis"),
        "denominator_axis_target": plan.get("target_axis"),
        "bridge_operator": "Bridge_R_localPi_posteriorC",
        "emission_matrix_registry_version": prior_hash,
        "bridge_mode": plan.get("mode") or "localPi_posterior",
        "missing_race_share": 0.0,
        "race_bridge_cv": 0.0,
        "sensitivity_width": 0.0,
        "race_axis_warning": "administrative_race_not_self_declared",
        "bayesian_ecological_bridge_warning": "local_pi_posterior_crosswalk",
        "prior_hash": prior_hash,
        "lower_count": 0.0,
        "upper_count": 0.0,
        "race_axis_target": plan.get("target_axis"),
    }
    lineage = make_lineage(
        parent_ids=[parent.id],
        operator_type="Bridge_R_localPi_posteriorC",
        operator_params=params,
        registry_versions={
            **dict(parent.lineage.registry_versions),
            "race_bridge_prior": str(prior_hash or "unknown"),
        },
        source_manifest_hashes=list(parent.lineage.source_manifest_hashes),
        code_version="slice28y_race_bridge_executor",
    )
    field = make_field_node(
        name=f"SIM race bridge posterior count {plan.get('bridge_id') or 'localPi'}",
        kind="bridge_module",
        carrier=parent.carrier,
        unit="counts",
        support=support,
        axes=axes,
        aggregation="additive",
        role=["race_bridge_posterior", "self_aligned_race_estimate", "source_field"],
        source=list(dict.fromkeys([*list(parent.source or []), "RaceBridgePrior", str(prior_path or "")])),
        operator="Bridge_R_localPi_posteriorC",
        provenance=list(dict.fromkeys([*list(parent.provenance or []), "BayesianEcologicalRaceBridge"])),
        state="fragile",
        warnings=["race_bridge_posterior_not_raw_epidemiological_observation"],
        lineage=lineage,
        materialization_state="metadata_only",
        path=None,
        dashboard_safe="warning",
    ).model_copy(update={"id": f"SIMRaceBridgePosteriorCount_{lineage_hash(lineage)[:24]}"})
    fields.append(field)
    operator = OperatorSpec(
        name="Bridge_R_localPi_posteriorC",
        role="race_bridge_posterior",
        output_kind="bridge_module",
        params=params,
    )
    edges.append(_edge(parent, field, operator))


def _field_domain_summaries(fields: Iterable[FieldNode], constraints: dict[str, Any]) -> dict[str, Any]:
    field_list = list(fields)
    summaries: dict[str, Any] = {}
    plan = constraints.get("race_bridge_plan")
    race_fields = [field for field in field_list if str(field.id).startswith("SIMRaceBridgePosteriorCount_")]
    if isinstance(plan, dict) and (plan.get("status") == "planned" or race_fields):
        race_support = race_fields[0].support if race_fields else {}
        summaries["race_bridge"] = {
            "bridge_id": plan.get("bridge_id") if isinstance(plan, dict) else race_support.get("bridge_id"),
            "mode": (plan.get("mode") if isinstance(plan, dict) else race_support.get("bridge_mode")) or "localPi_posteriorC",
            "prior_hash": plan.get("prior_hash") if isinstance(plan, dict) else race_support.get("prior_hash"),
            "source_axis": plan.get("source_axis") if isinstance(plan, dict) else race_support.get("source_axis"),
            "target_axis": plan.get("target_axis") if isinstance(plan, dict) else race_support.get("target_axis"),
            "missing_race_share": float(race_support.get("missing_race_share") or 0.0),
            "sensitivity_width": float(race_support.get("sensitivity_width") or 0.0),
            "race_bridge_cv": float(race_support.get("race_bridge_cv") or 0.0),
            "raw_admin_counts_preserved": True,
            "missing_category_preserved": True,
            "attach_stage": "efg_executor",
            "field_ids": [field.id for field in race_fields],
        }
    population_fields = [field for field in field_list if str(field.id).startswith("population_tensor_")]
    if population_fields:
        solver_fields = [field for field in population_fields if field.operator == "population_tensor_solver"]
        first = solver_fields[0] if solver_fields else population_fields[0]
        support = dict(first.support or {})
        mode = str(support.get("PopulationTensorMode") or "official_sidra_anchor")
        solver_id = str(support.get("SolverID") or "sidra_9606_total_anchor")
        solver_backend = "population_tensor_solver" if first.operator == "population_tensor_solver" else "official_sidra_anchor"
        summaries["population_tensor"] = {
            "schema_version": "1.0",
            "source_systems": ["SIDRA"],
            "attach_stage": "population_solver" if first.operator == "population_tensor_solver" else "standalone_population_tensor",
            "field_id": first.id,
            "tensor_id": first.id,
            "mode": mode,
            "solver_id": solver_id,
            "solver_backend": solver_backend,
            "denominator_feedback_warning": bool("sim_informed_population_feedback_risk" in set(first.warnings or [])) or None,
            "independent_denominator_mode": mode in {"official_sidra_anchor", "independent_denominator"},
            "sim_feedback_warning": "sim_informed_population_feedback_risk" if mode == "sim_informed_denominator" else None,
            "source_hashes": list(first.lineage.source_manifest_hashes),
        }
    cnes_fields = [field for field in field_list if "CNES-ST" in set(field.source or [])]
    sih_fields = [field for field in field_list if "SIH-RD" in set(field.source or [])]
    if cnes_fields or sih_fields:
        summaries["cnes_sih"] = {
            "schema_version": "1.0",
            "source_systems": ["CNES-ST", "SIH-RD"],
            "attach_stage": "she_build",
            "cnes": {
                "field_count": len(cnes_fields),
                "generic_beds_blocked": True,
            },
            "sih": {
                "field_count": len(sih_fields),
                "generic_sih_cost_blocked": True,
                "diagnostic_topology_preserved": True,
            },
        }
    sidra_context_fields = [field for field in field_list if field.operator == "sidra_context_field"]
    if sidra_context_fields:
        stdfm_fields = [field for field in sidra_context_fields if isinstance(field.support, dict) and field.support.get("stdfm") is not None]
        latent_fields = [field for field in sidra_context_fields if field.kind == "latent_context"]
        bound_fields = [
            field
            for field in sidra_context_fields
            if ((field.support or {}).get("high_dimensional_bound") or {}).get("status") == "bounded"
        ]
        summaries["sidra_context"] = {
            "schema_version": "1.0",
            "source_systems": ["SIDRA"],
            "attach_stage": "she_build",
            "field_count": len(sidra_context_fields),
            "context_gradient_count": len([field for field in sidra_context_fields if field.kind == "context_gradient"]),
            "latent_context_count": len(latent_fields),
            "stdfm_executed_count": len(stdfm_fields),
            "stdfm_certified_count": len([
                field for field in stdfm_fields
                if (((field.support or {}).get("stdfm") or {}).get("certification") or {}).get("status") in {"verified", "fragile"}
            ]),
            "high_dimensional_bounded_count": len(bound_fields),
            "projection_matrix_ids": sorted({
                str((field.support or {}).get("projection", {}).get("projection_matrix_id") or "")
                for field in sidra_context_fields
                if (field.support or {}).get("projection", {}).get("projection_matrix_id")
            }),
        }
    return summaries


def _dedupe_edges(edges: Iterable[EFGEdge], canonical: dict[str, str]) -> tuple[EFGEdge, ...]:
    output: dict[tuple[str, str, str], EFGEdge] = {}
    for item in edges:
        parent = canonical.get(item.parent_field_id, item.parent_field_id)
        child = canonical.get(item.child_field_id, item.child_field_id)
        if parent == child:
            continue
        key = (parent, child, item.operator)
        if key not in output:
            output[key] = EFGEdge(
                edge_id=f"edge_{content_hash(key)[:24]}",
                parent_field_id=parent,
                child_field_id=child,
                operator=item.operator,
                operator_params=item.operator_params,
                registry_versions=item.registry_versions,
                created_at=item.created_at,
            )
    return tuple(output.values())
